# handlers file
---
- name: new aliases
  ansible.builtin.command: >
    newaliases
  when: postfix_default_database_type != 'regexp'

- name: new virtual aliases
  ansible.builtin.command: >
    postmap {{ postfix_default_database_type }}:{{ postfix_virtual_aliases_file }}
  when: postfix_default_database_type != 'regexp'

- name: postmap sasl_passwd
  ansible.builtin.command: >
    postmap {{ postfix_default_database_type }}:{{ postfix_sasl_passwd_file }}
  when: postfix_default_database_type != 'regexp'

- name: postmap sender_canonical_maps
  ansible.builtin.command: >
    postmap {{ postfix_sender_canonical_maps_database_type }}:{{ postfix_sender_canonical_maps_file }}
  when: postfix_sender_canonical_maps_database_type != 'regexp'

- name: postmap recipient_canonical_maps
  ansible.builtin.command: >
    postmap {{ postfix_recipient_canonical_maps_database_type }}:{{ postfix_recipient_canonical_maps_file }}
  when: postfix_recipient_canonical_maps_database_type != 'regexp'

- name: postmap transport_maps
  ansible.builtin.command: >
    postmap {{ postfix_transport_maps_database_type }}:{{ postfix_transport_maps_file }}
  when: postfix_transport_maps_database_type != 'regexp'

- name: postmap sender_dependent_relayhost_maps
  ansible.builtin.command: >
    postmap {{ postfix_default_database_type }}:{{ postfix_sender_dependent_relayhost_maps_file }}
  when: postfix_default_database_type != 'regexp'

- name: postmap generic
  ansible.builtin.command: >
    postmap {{ postfix_smtp_generic_maps_database_type }}:{{ postfix_smtp_generic_maps_file }}
  when: postfix_smtp_generic_maps_database_type != 'regexp'

- name: remove pid
  ansible.builtin.file:
    path: "~postfix/pid/master.pid"
    state: absent
  listen: restart postfix
  when: is_docker_guest

- name: restart service
  ansible.builtin.service:
    name: postfix
    state: restarted
  listen: restart postfix
  when: service_default_state | default('started') == 'started'
