# handlers file for postfix
---
- name: new aliases
  command: newaliases

- name: new virtual aliases
  command: postmap {{ postfix_default_database_type }}:{{ postfix_virtual_aliases_file }}

- name: postmap sasl_passwd
  command: postmap -p {{ postfix_default_database_type }}:{{ postfix_sasl_passwd_file }}

- name: postmap sender_canonical_maps
  command: postmap {{ postifx_sender_canonical_maps_database_type }}:{{ postfix_sender_canonical_maps_file }}

- name: postmap recipient_canonical_maps
  command: postmap {{ postfix_default_database_type }}:{{ postfix_recipient_canonical_maps_file }}

- name: postmap transport_maps
  command: postmap {{ postfix_default_database_type }}:{{ postfix_transport_maps_file }}

- name: postmap sender_dependent_relayhost_maps
  command: postmap {{ postfix_default_database_type }}:{{ postfix_sender_dependent_relayhost_maps_file }}

- name: postmap generic
  command: postmap {{ postfix_default_database_type }}:{{ postfix_generic_file }}

- name: remove pid
  file:
    path: "~postfix/pid/master.pid"
    state: absent
  listen: restart postfix
  when: is_docker_guest

- name: restart service
  service:
    name: postfix
    state: restarted
  listen: restart postfix
  when: service_default_state | default('started') == 'started'
